### ISSUE TITLE
MD-380 is not supported

### ISSUE THREAD

**Issue by khaytsus** [sergev/dmrconfig#1] opened 2018-09-02 20:42 UTC
I hope this is the right avenue to have a discussion about the MD-380, let me know what information I can provide to help you here.  I am using an MD-380 with the MD380 Tools firmware, using this method:  https://github.com/KD4Z/md380tools-vm

wally@lamneth 16:25 [dmrconfig]% ./dmrconfig -r -t
--- Send GETSTATE [1]
--- Send DNLOAD [2] 91-01
--- Send GETSTATUS [6]
--- Send GETSTATE [1]
--- Send ABORT
--- Send GETSTATE [1]
--- Send DNLOAD [2] a2-01
--- Send GETSTATUS [6]
--- Send GETSTATE [1]
--- Send ABORT
--- Send GETSTATE [1]
--- Send UPLOAD [64]
--- Send GETSTATUS [6]
--- Send DNLOAD [5] 21-00-00-00-00
--- Send GETSTATUS [6]
--- Send GETSTATE [1]
--- Send ABORT
--- Send GETSTATE [1]
Connect to DR780.
Unrecognized radio 'DR780'.

Just to see what happens if I modified radio.c to accept DR780.  It did download and the files look sane.  I'll attach them for you to look at.  I did notice the radio stayed in the "Programing" mode screen, where editcp the radio reboots back into normal mode after a download or upload to the radio.  I did not attempt to upload the code into the radio using dmrconfig.

Interestingly, I see a lot of contacts in the list that I didn't expect.  Perhaps they are the large user database uploaded to the radio using the custom firmware?  Entry 62 (Ireland) is the last that show in my Contacts list on the radio or in editcp.

[md380.zip](https://github.com/sergev/dmrconfig/files/2343736/md380.zip)

**Comment by khaytsus** [comment] 2018-09-02 20:59
Just a few notes from quickly looking over the text file..  I'm unclear on how the columns are tabulated, is it purely space between each column and the extra spaces are purely for human readability?  

Now; issues...  In the analog channels there are a lot showing (null), such as channel 916, which is 25khz.  Channel 951 is 12.5khz, and it shows 20.  

Channel 907 TOT shows 3060.  Not sure where this comes from, it appears to be 180 like every other channel I have.  This continues through the rest of the digital channels, except starting at 948 and then 978 the last two digital channels it's 3000.  Again, appears to be 180 in editcp.  And then the analog all show TOT as 3000 or 3060.  Again, all 180 as far as I can tell in editcp.

I did not look overly close at some of the other areas such as lists of channels in a scan group etc but so far looks sane.

**Comment by sergev** [comment] 2018-09-04 20:06
Perfect: thank you so much for the bug report, Walter. Attached device.img file helps a lot. The result in device.conf looks not bad, just a few issues to fix.
(1) TOT column: wrong values 3060 and 3000.
(2) InCall column: incorrectly decoded value "???" for digital channels 907-978.
(3) Width column: incorrectly decoded values "(null)" for analog channels 916-950. Also 20 instead of 12.5 for channel 951.
(4) Ugly channel numbers in zones 15, 16, 23, 27, 45.
(5) Unexpected contacts with type=0.

As for Programming mode, I need to study the editcp code and figure out how it switches the radio back to normal at end of session.

The unexpected contacts 63-1000 are caused by incorrect interpretation of contact type = 0, which should mean the contact has been deleted. I'll fix that.

Fields in tables can be separated by any amount of spaces or tabs. It's all just to make it more readable. The whole point is to make the configuration easy to grasp without additional software.

**Comment by sergev** [comment] 2018-09-05 04:27
Seems like editcp sometimes puts wrong values into some fields. When I open your codeplug device.img with the official CPS and browse through the channels, I can see some fields empty, which means wrong values. See attached snapshot for channel 907.
![cps-channel907](https://user-images.githubusercontent.com/1139878/45071062-505bc600-b089-11e8-81f6-84a014f58b48.png)

**Comment by sergev** [comment] 2018-09-05 06:07
Bandwidth is correct in dmrconfig and wrong in editcp. Here is a screenshot of channel 916 opened in official TYT CPS. Field Bandwidth is empty, which means incorrect setting. That's why dmrconfig shows null. I'll modify it to show 25khz instead.

![cps-channel916](https://user-images.githubusercontent.com/1139878/45074062-d3cfe400-b096-11e8-871e-51e7d95429cf.png)

For channel 951, CPS shows 20khz, as well as dmrconfig. Editcp is wrong.

![cps-channel951](https://user-images.githubusercontent.com/1139878/45074156-3aed9880-b097-11e8-8b35-0355332ff6ba.png)

**Comment by DaleFarnsworth** [comment] 2018-09-05 15:18
Thanks Serge.  In editcp, I have fixed the TOT value and the Rx/Tx Signalling System.  However, in the md380/md390 CPS, the only two bandwidth options are 12.5 and 25 KHz.  I see that the md-uv380 and the md2017 CPS also have a 20KHz option.  It looks like a 1-bit field is used for the md380 and a 2-bit field is used for the md-uv380.  I'm glad to have someone else writing dmr config sw.

**Comment by sergev** [comment] 2018-09-05 18:43
Sure, Dale! Thank you for your great editcp tool. Your sources helped me to figure out some details of RDT file format. 
I spent some time analyzing hexdump of md-uv380 and md380 files. There are many subtle differences. You can find my results in a form of a C data structure here:
https://github.com/sergev/dmrconfig/blob/master/md380.c#L67
https://github.com/sergev/dmrconfig/blob/master/uv380.c#L68

I use MD380 CPS version 1.34. It offers three options for bandwidth for analog channels: 12.5kHz, 20kHz and 25kHz. Here is a screenshot:

![md380-analog-bandwidth](https://user-images.githubusercontent.com/1139878/45113990-af105680-b100-11e8-9451-55c85c0bb596.png)

**Comment by sergev** [comment] 2018-09-05 20:08
@khaytsus : I believe I've fixed everything in version #4ea032d5ca24b76e030522cbbb30091774289ca0. Can you please check that it works for you? Thanks.

**Comment by DaleFarnsworth** [comment] 2018-09-07 05:43
Interesting. The md380 v1.34 CPS I used doesn't have 20 KHz.  However I tried a v1.37 and it shows all 3 bandwidth settings.  I have change it to a 2-bit field in my current editcp and support all 3 bandwidths.  The hardest part of adding uv380 support to editcp is getting the codeplug layout.  I should be able to extract that from your code.  Thanks.

**Comment by sergev** [comment] 2018-09-11 20:20
No news from Walter for a week, so I guess MD-380 is fine. I'm closing the ticket: please reopen it in case of any issues.

**Closed by sergev** 2018-09-11 20:20 UTC
Labels: bug, in test
